openapi: 3.0.0
info:
  title: Messari Market Data API
  version: 1.0.0
  description: API for accessing market data for assets

paths:
  /marketdata/v1/assets/roi:
    get:
      operationId: getAssetsROI
      summary: Returns a list ROI data for all assets
      description: Returns a list ROI data for all assets
      tags:
        - Asset Data
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssetWithROIData'
        '4XX':
          description: Client error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'
        '500':
          description: Server error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'

  /marketdata/v1/assets/ath:
    get:
      operationId: getAssetsATH
      summary: Returns a list of all time high data for all assets
      description: Returns a list of all time high data for all assets
      tags:
        - Asset Data
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssetWithATHData'
        '4XX':
          description: Client error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'
        '500':
          description: Server error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'

  /marketdata/v1/assets/{assetId}/price:
    get:
      operationId: getAssetPrice
      summary: Returns a single asset's market data
      description: Returns a single asset's market data
      tags:
        - Asset Data
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
          description: Asset ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetMarketData'
        '4XX':
          description: Client error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'
        '500':
          description: Server error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'

  /marketdata/v1/assets/{assetId}/roi:
    get:
      operationId: getAssetROI
      summary: Returns a single asset's ROI data
      description: Returns a single asset's ROI data
      tags:
        - Asset Data
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
          description: Asset ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetWithROIData'
        '4XX':
          description: Client error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'
        '500':
          description: Server error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'

  /marketdata/v1/assets/{assetId}/ath:
    get:
      operationId: getAssetATH
      summary: Returns a single asset's ATH data
      description: Returns a single asset's ATH data
      tags:
        - Asset Data
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
          description: Asset ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetWithATHData'
        '4XX':
          description: Client error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'
        '500':
          description: Server error response
          content:
            application/json:
              schema:
                $ref: '../../common/components.yaml#/components/schemas/APIError'

components:
  schemas:
    TimeUTC:
      type: string
      format: date-time
      description: UTC timestamp
      
    OHLCV:
      type: object
      properties:
        open:
          type: number
          format: double
        high:
          type: number
          format: double
        low:
          type: number
          format: double
        close:
          type: number
          format: double
        volume:
          type: number
          format: double
        timestamp:
          $ref: '#/components/schemas/TimeUTC'

    PlatformContract:
      type: object
      properties:
        platform:
          type: string
        contractAddress:
          type: string

    MarketDataAsset:
      type: object
      properties:
        id:
          type: string
        serialId:
          type: integer
          format: int32
        symbol:
          type: string
        name:
          type: string
        slug:
          type: string
        contractAddresses:
          type: array
          items:
            $ref: '#/components/schemas/PlatformContract'

    AssetSupply:
      type: object
      properties:
        max:
          type: number
          format: double
        total:
          type: number
          format: double
        circulating:
          type: number
          format: double

    AssetMarketcap:
      type: object
      properties:
        circulatingUsd:
          type: number
          format: double
        fullyDilutedUsd:
          type: number
          format: double
        dominance:
          type: number
          format: double

    AssetMarketData:
      type: object
      properties:
        priceUsd:
          type: number
          format: double
        lastPriceAt:
          $ref: '#/components/schemas/TimeUTC'
        priceBtc:
          type: number
          format: double
        priceEth:
          type: number
          format: double
        volume24Hours:
          type: number
          format: double
        realVolume24Hours:
          type: number
          format: double
        volume24HoursOverstatementMultiple:
          type: number
          format: double
        percentChangeUsd1Hour:
          type: number
          format: double
        percentChangeBtc1Hour:
          type: number
          format: double
        percentChangeEth1Hour:
          type: number
          format: double
        percentChangeUsd24Hours:
          type: number
          format: double
        percentChangeBtc24Hours:
          type: number
          format: double
        percentChangeEth24Hours:
          type: number
          format: double
        ohlcv1Hour:
          $ref: '#/components/schemas/OHLCV'
        ohlcv24Hours:
          $ref: '#/components/schemas/OHLCV'
        lastTradeAt:
          $ref: '#/components/schemas/TimeUTC'
        supply:
          $ref: '#/components/schemas/AssetSupply'
        marketcap:
          $ref: '#/components/schemas/AssetMarketcap'

    ROIData:
      type: object
      properties:
        percentChange1Week:
          type: number
          format: double
        percentChange1Month:
          type: number
          format: double
        percentChange3Months:
          type: number
          format: double
        percentChange1Year:
          type: number
          format: double
        percentChangeBtc1Week:
          type: number
          format: double
        percentChangeBtc1Month:
          type: number
          format: double
        percentChangeBtc3Months:
          type: number
          format: double
        percentChangeBtc1Year:
          type: number
          format: double
        percentChangeEth1Week:
          type: number
          format: double
        percentChangeEth1Month:
          type: number
          format: double
        percentChangeEth3Months:
          type: number
          format: double
        percentChangeEth1Year:
          type: number
          format: double
        percentChangeMonthToDate:
          type: number
          format: double
        percentChangeQuarterToDate:
          type: number
          format: double
        percentChangeYearToDate:
          type: number
          format: double

    AssetWithROIData:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        symbol:
          type: string
        slug:
          type: string
        contractAddresses:
          type: array
          items:
            $ref: '#/components/schemas/PlatformContract'
        roiData:
          $ref: '#/components/schemas/ROIData'

    AssetWithATHData:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        symbol:
          type: string
        slug:
          type: string
        contractAddresses:
          type: array
          items:
            $ref: '#/components/schemas/PlatformContract'
        allTimeHighData:
          type: object
          properties:
            price:
              type: number
              format: double
            at:
              $ref: '#/components/schemas/TimeUTC'
            daysSince:
              type: number
              format: double
            percentDown:
              type: number
              format: double
            breakevenMultiple:
              type: number
              format: double
        cycleLowData:
          type: object
          properties:
            price:
              type: number
              format: double
            at:
              $ref: '#/components/schemas/TimeUTC'
            percentUp:
              type: number
              format: double
            daysSince:
              type: number
              format: double
  
